### ISSUE TITLE
Visual studio code support

### ISSUE THREAD

**Issue by marty-wang** [trevordmiller/nova-colors#15]
Any plan to support visual studio code?

**Comment by trevordmiller** [comment]
@marty-wang Not currently. Feel free to build it though if you'd like! There are contributing instructions on https://trevordmiller.github.io/nova.

**Comment by hgwood** [comment]
2 extensions exist for VS code : https://marketplace.visualstudio.com/search?term=nova&target=VSCode&sortBy=Relevance

**Comment by trevordmiller** [comment]
@hgwood The community has started building a VSCode plugin in https://github.com/trevordmiller/nova-colors/issues/18. @rebornix (on the VSCode team) is heading it up. I haven't added it to the Nova website yet because it isn't fully using Nova color values + Nova color meanings yet. Although Nova is fully open source and people can fork it however they'd like, I would encourage using the version built by @rebornix; @igetgames would you consider removing or renaming yours to avoid confusion?

**Comment by trevordmiller** [comment]
Also, the "Nova Color Theme" version by AKT isn't following the Nova color meanings and isn't using the right logo; I wouldn't recommend it if you want to use Nova as defined on https://trevordmiller.github.io/nova.

**Comment by trevordmiller** [comment]
Hey @rebornix, fyi, the other Nova theme has more downloads ![image](https://cloud.githubusercontent.com/assets/5497885/18843295/66ec30b8-83d5-11e6-8031-7ec2531a90bf.png). I'm looking forward to your's implementing the rest of the Nova color values and meanings so we can add it to the Nova website and direct people to the "blessed" plugin :) Let me know when you are ready. Thanks.

**Comment by igetgames** [comment]
@trevordmiller The other Nova theme by AKT isn't mine, my version was never published.

**Comment by trevordmiller** [comment]
@igetgames Oh ok, sorry about the mixup! Thanks for letting me know.

**Comment by hgwood** [comment]
@trevordmiller Thank you for the pointers!

**Comment by trevordmiller** [comment]
@trevordmiller No problem, I just want to make sure your work is promoted officially when ready, let me know :)
